config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/index'

  resources :relationships, only: [:create, :destroy]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  get 'comments/create'
  
  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end
  
  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  resources :poems, only: [:index, :show]

  resources :poemhers, only: [:index, :show]

  resources :users, only: [:index, :show]

  resources :conversations do
    resources :messages
  end

end

app/models/poemher.rb
class Poemher
  include Her::Model
end

app/controllers/poemhers_controller.rb
class PoemhersController < ApplicationController
  def index
    @poemhers = Poem.all
  end

  def show
    @poemher = Poem.find(params[:id])
  end
  
end

app/helpers/poemhers_helper.rb
module PoemhersHelper
end

app/views/poemhers/index.html.erb
<h1>ポエム一覧(her使用)</h1>
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<table>
  <tr>
    <td>タイトル</td>
    <td>内　　容</td>
    <td></td>
  </tr>
<% @poemhers.each do |poemher| %>
<tr>
  <td class="poemtitle"><%= poemher.title %></td>
  <td class="poemcontent"><%= poemher.content %></td>
  <td class="poembtn"><%= link_to "詳細ページ", poemher_path(poemher.id), class: 'btn btn-default btn-sm btn-success' %></td>
</tr>
<% end %>
</table>
</div>
</div>

app/views/poemhers/show.html.erb
<h1>ポエム詳細(her使用)</h1>
<div>
  <p>タイトル： <%= @poemher.title %></p>
  <p>内　　容： <%= @poemher.content %></p>
</div>